# Generated by Django 4.2.11 on 2024-05-16 13:09

import custom_fields.multiselect_with_other.db.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onboarding', '0035_userextendedprofile_hubspot_contact_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='metricupdatepromptrecord',
            name='click',
            field=models.CharField(choices=[('RML', 'Remind Me Later'), ('TMT', 'Take Me There'), ('NT', "No Thanks, I'm Not Interested")], db_index=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_organization_registered',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Is Organization Registered as 501c3?'),
        ),
        migrations.AlterField(
            model_name='organizationmetric',
            name='actual_data',
            field=models.BooleanField(blank=True, choices=[(False, 'Estimated - My answers are my best guesses based on my knowledge of the organization'), (True, "Actual - My answers come directly from my organization's official documentation")], null=True),
        ),
        migrations.AlterField(
            model_name='organizationmetricupdateprompt',
            name='remind_me_later',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='userextendedprofile',
            name='function_areas',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('function_strategy_planning', 'Strategy and planning'), ('function_leadership_governance', 'Leadership and governance'), ('function_program_design', 'Program design and development'), ('function_measurement_eval', 'Measurement, evaluation, and learning'), ('function_stakeholder_engagement', 'External relations and partnerships'), ('function_human_resource', 'Human resource management'), ('function_financial_management', 'Financial management'), ('function_fundraising', 'Fundraising and resource mobilization'), ('function_marketing_communication', 'Marketing, communications, and PR'), ('function_system_tools', 'Systems, tools, and processes')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userextendedprofile',
            name='goals',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('goal_contribute_to_org', 'Help improve my organization'), ('goal_gain_new_skill', 'Develop new skills'), ('goal_improve_job_prospect', 'Get a job'), ('goal_relation_with_other', 'Build relationships with other nonprofit leaders')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userextendedprofile',
            name='hear_about_philanthropyu',
            field=custom_fields.multiselect_with_other.db.fields.MultiSelectWithOtherField(blank=True, choices=[('hear_about_philanthropy_partner', 'A Philanthropy University Partner (Global Giving, +Acumen or another)'), ('hear_about_colleague_same_organization', 'A Colleague From My Organization'), ('hear_about_friend_new_organization', 'A Friend Or Colleague (Not From My Organization)'), ('hear_about_internet_search', 'An Internet Search'), ('hear_about_linkedIn_advertisement', 'A LinkedIn Advertisement'), ('hear_about_facebook_advertisement', 'A Facebook Advertisement'), ('hear_about_twitter_not_colleague', 'Twitter (Not From A Colleague)'), ('other', 'Other')], max_length=488),
        ),
        migrations.AlterField(
            model_name='userextendedprofile',
            name='hours_per_week',
            field=models.PositiveIntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(168)], verbose_name='Typical Number of Hours Worked per Week*'),
        ),
        migrations.AlterField(
            model_name='userextendedprofile',
            name='interests',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('interest_strategy_planning', 'Strategy and planning'), ('interest_leadership_governance', 'Leadership and governance'), ('interest_program_design', 'Program design and development'), ('interest_measurement_eval', 'Measurement, evaluation, and learning'), ('interest_stakeholder_engagement', 'External relations and partnerships'), ('interest_human_resource', 'Human resource management'), ('interest_financial_management', 'Financial management'), ('interest_fundraising', 'Fundraising and resource mobilization'), ('interest_marketing_communication', 'Marketing, communications, and PR'), ('interest_system_tools', 'Systems, tools, and processes')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userextendedprofile',
            name='learners_related',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('learners_same_region', 'Learners from my region or country'), ('learners_similar_oe_interest', 'Learners interested in same areas of organization effectiveness'), ('learners_similar_org', 'Learners working for similar organizations'), ('learners_diff_who_are_different', 'Learners who are different from me')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userextendedprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extended_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
